### ISSUE TITLE
Reverse timer

### ISSUE THREAD

**Issue by xinhash** [ryanhefner/react-timer-wrapper#29]
Let say we have 45 min duration. How can we implement reverse countdown for this ?

**Comment by ryanhefner** [comment]
Hi, @xinhash. Yeah, you can set the `duration` prop and that will enable countdown mode. So, for instance:
```js
<Timer duration={45 * 60 * 1000} onFinish={this.onFinish} />
```
That should countdown from 45 min and fire the `onFinish` handler when done. Let me know if you run into any issues with that. Feel free to close this issue out if that works for you.

Thanks!

**Comment by xinhash** [comment]
Hi. It's not starting from 45 and moving to 0.

**Comment by ryanhefner** [comment]
Hi @xinhash,

Sorry for the confusion. The `time` itself will start at `0` and increment as the `Timer` is `active`. But, the `onFinish` will fire once it has reached the `duration`. I updated the example site to show how you could handle it. Let me know if you have any other questions or thoughts on it.

https://ryanhefner.github.io/react-timer-wrapper/

**Comment by ryanhefner** [comment]
@xinhash Did that help?

**Comment by ryanhefner** [comment]
@xinhash Feel free to reopen this if you’d like to talk through some other possible solutions. Hope it’s working for you!
